# Based on https://developer.hashicorp.com/terraform/tutorials/automation/github-actions
# See the article for details
name: 'Terraform'

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

env:
  TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}

jobs:
  check:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v18

    - run: nix profile install .#terraform

    - run: terraform version

    - run: terraform fmt -check

    - run: terraform init

    - run: terraform validate

  plan_or_apply:
    needs: check
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v18

    - run: nix profile install .#terraform

    - run: terraform init

    - run: terraform plan
      if: github.event_name == 'pull_request'

    - run: terraform apply -auto-approve -input=false
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
