name: 'Terraform Apply'

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}

jobs:
  check:
    uses: ./.github/workflows/terraform-check.yml
    with:
      ref: ${{ github.ref }}

  prod:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
    - run: echo "Deploying to production"

  apply:
    needs: ['check', 'prod']
    runs-on: ubuntu-latest

    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}

    steps:

    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v18

    - run: nix profile install .#terraform

    - run: terraform init

    - name: Create a private key for remote-exec
      run: |
        echo "$PRIVATE_KEY" > terraform-cloud.pem
        chmod 600 terraform-cloud.pem
      env:
        PRIVATE_KEY: ${{secrets.TARGET_PRIVATE_KEY}}

    - run: terraform validate

    - run: terraform apply -auto-approve -input=false
