name: 'Terraform Apply'

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  check:
    uses: ./.github/workflows/terraform-check.yml
    with:
      ref: ${{ github.ref }}

  prod:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
    - run: echo "Deploying to production"

  apply:
    needs: ['check', 'prod']
    runs-on: ubuntu-latest

    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}

    steps:

    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v31

    - run: nix profile install .#opentofu

    - run: tofu init

    - run: tofu validate

    - run: tofu apply -auto-approve -input=false
