name: 'Terraform Destroy'

on:
  workflow_dispatch:

jobs:
  check:
    uses: ./.github/workflows/terraform-check.yml
    with:
      ref: ${{ github.ref }}

  apply:
    needs: ['check']
    runs-on: ubuntu-latest

    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}

    steps:

    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v18

    - run: nix profile install .#terraform

    - run: terraform init

    - run: terraform validate

    - run: terraform apply -destroy -auto-approve -input=false
