name: 'Terraform Plan'

on:
  pull_request:

jobs:
  check:
    uses: ./.github/workflows/terraform-check.yml
    with:
      ref: ${{ github.ref }}

  plan:
    needs: check
    runs-on: ubuntu-latest

    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}

    steps:

    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v30

    - run: nix profile install .#opentofu

    - run: tofu init

    - run: tofu validate

    - uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
      with:
        tfsec_args: --soft-fail
        github_token: ${{ github.token }}

    - run: tofu plan
