name: 'Terraform Destroy'

on:
  workflow_dispatch:

jobs:
  check:
    uses: ./.github/workflows/terraform-check.yml
    with:
      ref: ${{ github.ref }}

  plan:
    needs: check
    runs-on: ubuntu-latest

    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}

    steps:

    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v18

    - run: nix profile install .#terraform

    - run: terraform init

    - run: terraform destroy -auto-approve -input=false
      env:
        TF_VAR_hcloud_token: ${{secrets.TF_VAR_HCLOUD_TOKEN}}
        TF_VAR_public_key: ${{secrets.TF_VAR_PUBLIC_KEY}}
