name: 'Terraform Plan'

on:
  pull_request:

jobs:
  check:
    uses: ./.github/workflows/terraform-check.yml
    with:
      ref: ${{ github.ref }}

  plan:
    needs: check
    runs-on: ubuntu-latest

    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}

    steps:

    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          accept-flake-config = true

    - run: nix profile install .#terraform

    - run: terraform init

    - run: terraform validate

    - uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
      with:
        tfsec_args: --soft-fail
        github_token: ${{ github.token }}

    - run: terraform plan
